### ISSUE TITLE
Microsoft.VCToolsVersion.default.txt not found

### ISSUE THREAD

**Issue by pemo11** [harborsiem/WindowsRibbon#11]
Why is Microsoft.VCToolsVersion.default.txt still needed for versions number check?

This file is obviously not part of VS 2022 and VS 2022 Build tools anymore.

If I create the file and put an arbitrary version number in it a 0  byte ribbon file will be created and the log file is empty.

**Comment by harborsiem** [comment]
Did you install the C++ Development Tools for VS 2022 ?
In my VS 2022 Community Edition 17.5.3 there is a Microsoft.VCToolsVersion.default.txt file. The content of this file is 14.35.32215

**Comment by pemo11** [comment]
I only installed the Visual Studio 2022 Build tools and my Visual Studio installation was split between drive c and d, so there was no MSVC subdirectory on the C drive. I copied the existing directory from D to C. Now it works.
