### ISSUE TITLE
RibbonTools not working with the latest VisualStudio 2022

### ISSUE THREAD

**Issue by xieguigang** [harborsiem/WindowsRibbon#12]
Hi, 

Many thanks to this greate windows UI project. I here report a compatibility problem between the ribbontools and the latest version of VisualStudio. The VC redist version text file its file path has been updated recently, so current ribbontools will not able to be opened(it crashed once it has been launch).

By debug the ribbontools in vs I found that due to the reason of file path that defined in ribbontools ``C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt`` has been changed to ``C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt`` in the latest version of visualstudio, so this change will crash the ribbiontools.

![vs_debug](https://github.com/harborsiem/WindowsRibbon/assets/9410171/5f298dfb-8b0d-48d5-ad67-2683c3e7e7a2)
![vs_vc_latest](https://github.com/harborsiem/WindowsRibbon/assets/9410171/37c1dcbf-29e0-4384-8670-68addac077fc)
![stacktrace](https://github.com/harborsiem/WindowsRibbon/assets/9410171/c1b7e673-50a5-41ee-9245-9cd78e1d19f9)

Hope this helpful

**Comment by xieguigang** [comment]
``LinkerRightButtonClick`` also has bug when the linkerText is empty, in this situation the user can never set the location of ``link.exe`` when the linkerText is empty at very begining.

![link](https://github.com/harborsiem/WindowsRibbon/assets/9410171/3fd4f123-fe08-48e8-b51f-67504cd21596)

**Comment by harborsiem** [comment]
At my computer there is a file Microsoft.VCToolsVersion.default.txt. My latest VisualStudio 2022 version is 17.6.2.
I think you don't install "Desctop development for C++". Therefore you don't get the file Microsoft.VCToolsVersion.default.txt. 
Here you can see my file directory:
![VC_Auxiliary_Build](https://github.com/harborsiem/WindowsRibbon/assets/28147549/68efc0f5-31f8-4676-b243-28cae731f23c)

I will think about a MessageBox information for the user in this case.
The second issue with empty linkerText I will change in the next version of the RibbonTools.
Thank you for helping.

**Comment by xieguigang** [comment]
Hi，

Errrr, yes I found myself make a mistake: I haven't install the C++ development component in VisualStudio，so ribbontools not working due to the reason of lack of compiler tool for ribbon. After i have install the C++ environment, every thing works!

many thanks to the reply, and by the way, this Ribbon library it really looks very nice for windows application:

![Capture](https://github.com/harborsiem/WindowsRibbon/assets/9410171/64f10024-8e2c-4b17-b5cf-0d29d5df89cf)
> here is my open source windows industry software work recently, UI is based on your WindowsRibbon library

many thanks again
