### ISSUE TITLE
Have you considered multi-language support?

### ISSUE THREAD

**Issue by kelilive** [harborsiem/WindowsRibbon#16]
Hello,

How to control the buttons inside the QuickAccessToolbar, I can't fully control it.

I want to know how to control the bottom three options. I tried using RibbonTool.exe, but it seems that the control of the three option buttons Show Below the Ribbon, More commands..., Minimize the Ribbon is missing.

If I can control them, I can better accomplish what I want to do.

1. To achieve multi-language, I can modify the displayed interface text by controlling the language options.
2. I want to know how to adjust the order, for example, More commands. I don’t know how they were added here and how I can control where they are added. I know how to add ordinary buttons, but I still have insufficient knowledge about this special usage.

Tips: No matter whether I try to set the display language through code or modify the windows system language, I seem to find that I cannot change the displayed language text.

![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/78b4e5b7-4598-4540-b340-5a2061ae4290)
![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/59fb8064-2e60-4d69-a8dc-968b8c47609f)

Thanks.

**Comment by harborsiem** [comment]
Hello
You can't change the buttons order and text of "Show below the Ribbon", "More Commands...", "Minimize the Ribbon". It is fixed part of the Ribbon Framework. The text language of these buttons  is depending to the installed Windows language. See installed German language:
![Qat_German](https://github.com/harborsiem/WindowsRibbon/assets/28147549/f9d02b99-fe9a-414c-9dff-0990832648f6)

**Comment by kelilive** [comment]
You are right, this needs to be restarted to take effect. I may have simply logged out before and nothing seems to have changed.
