### ISSUE TITLE
Usability improvements or improved documentation?

### ISSUE THREAD

**Issue by kelilive** [harborsiem/WindowsRibbon#17]
**Question 1:**
If the Ribbon resource name is not set correctly, it will not work properly. When I looked at the example, I found that Ribbon set the ResourceName attribute, but this attribute is not a very intuitive string. I use ILSPY to check the names I know, so is there any more reliable and convenient solution? If there is no improvement here, the documentation should be improved to help newcomers get better familiar with it. 

When the user resource string is incorrectly bound, should a more intuitive and understandable Exception be prompted at runtime? Instead of NullReferenceException? Because developers are more sensitive to message anomalies that are more readable.

**Question 2:**
Another problem is that after the Ribbon is dragged and placed, setting the height does not seem to change. If this is the case, should it be replaced by that component method? What about the component area displayed at the bottom of the designer? 

**Question 3:**
When ResourceName is not specified, it will be a little strange. Should the program not draw at this time? If it must be drawn, it should at least change with the window change. There appear to be some display issues at the moment. The width does not change, it should change. The height seems to have an effect, but this effect does not seem to make any sense.

![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/b9c0766d-55d1-48d5-8c47-501a87aea6c8)

**Comment by harborsiem** [comment]
#Question 1:
Setting ResourceName property is described in HowToUse.md (14.). Maybe also in a Wiki document. A better property name may be RibbonResource. I don't want to change because of compatibility.

> When the user resource string is incorrectly bound, should a more intuitive and understandable Exception be prompted at runtime? Instead of NullReferenceException? Because developers are more sensitive to message anomalies that are more readable.

What do you mean with incorrect bound? Can you send a small project? NullReferenceException should not occur.

#Question 2:
You can't change the height or width of the Ribbon for the runtime. Have a look to event RibbonHeightChanged in the Ribbon class.
It's a good idea with placing as a component like MenuStrip. But my knowledge to do this is very poor. Maybe I have to do work for the Framework designer and also for the .NET Core designer. Pull request welcome.

#Question 3:
Maybe it will be easier for users, that an ApplicationException is thrown when the ResourceName is not specified.

**Comment by kelilive** [comment]
> What do you mean with incorrect bound? Can you send a small project? NullReferenceException should not occur.

Debug mode:
![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/78709da2-0dce-4412-8b53-0d682e0d0fbc)

Release mode:
![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/eede0cc3-2931-4bc1-b41d-5280b97cf234)

**Comment by kelilive** [comment]
In addition, I have a question about display. When the two attribute strings do not appear at the same time, they should be vertically centered, otherwise it will feel a bit strange.

The string title and description content of the floating prompt also seem to be a bit inelegant. I feel it intuitively. Maybe there is some software that can refer to it.

Does it mean that these two Label attributes must exist together? I don’t think so. Users should be allowed to do this. When editing through RibbonTool, the content should be verified, and at least a Label Title and a Label Description must exist. When drawing and parsing, a layer of verification is performed to avoid external modifications and ensure consistency.
When an attribute exists, it should also be vertically centered, which may work better.

![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/4c04f694-50c9-42de-b028-5ca202f8a71d)
![image](https://github.com/harborsiem/WindowsRibbon/assets/142982913/f584144f-9d0e-4944-a38e-e61de2b75f31)

Also, the string length should be limited when editing with RibbonTools.

**Comment by harborsiem** [comment]
> In addition, I have a question about display. When the two attribute strings do not appear at the same time, they should be vertically centered, otherwise it will feel a bit strange.
> 
> The string title and description content of the floating prompt also seem to be a bit inelegant. I feel it intuitively. Maybe there is some software that can refer to it.
> 
> Does it mean that these two Label attributes must exist together? I don’t think so. Users should be allowed to do this. When editing through RibbonTool, the content should be verified, and at least a Label Title and a Label Description must exist. When drawing and parsing, a layer of verification is performed to avoid external modifications and ensure consistency. When an attribute exists, it should also be vertically centered, which may work better.
> 
> ![image](https://private-user-images.githubusercontent.com/142982913/317567437-4c04f694-50c9-42de-b028-5ca202f8a71d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTA1OTgsIm5iZiI6MTcxMTYxMDI5OCwicGF0aCI6Ii8xNDI5ODI5MTMvMzE3NTY3NDM3LTRjMDRmNjk0LTUwYzktNDJkZS1iMDI4LTVjYTIwMmY4YTcxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNzE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjk4NTk5ZDMxMTEyNjNkNGQzZmY5NmVkMzEwM2FjZTBmZmVjZmIyMTA2YWZiOWM2Mjk3ZDU4NmZlOTQ4ZjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9aRdDW_p1-HsxIVfE9wAg60fk_FYWXlhxSvrDAa-OGI) ![image](https://private-user-images.githubusercontent.com/142982913/317567554-f584144f-9d0e-4944-a38e-e61de2b75f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTA1OTgsIm5iZiI6MTcxMTYxMDI5OCwicGF0aCI6Ii8xNDI5ODI5MTMvMzE3NTY3NTU0LWY1ODQxNDRmLTlkMGUtNDk0NC1hMzhlLWU2MWRlMmI3NWYzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNzE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzFlMzZhMThhYTM3ODU0ZWVmYzhhYjA3ZjAzYzhiNjUzMDFlMGViNmQ4ZjA2NjBmZjlhYmIxNmNmYzliYzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AlmPGuFi0NzUWYhd2Sc9JpZopeMeJbcgRDUYNkkmTRU)
> 
> Also, the string length should be limited when editing with RibbonTools.

Rendering is part of Microsoft Ribbon Framework. see [LabelDescription](https://learn.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-reference-properties-uipkey-labeldescription)
RibbonTools is just a helper tool for the xml stuff that Microsoft delivers for designing a Ribbon.
I think that the Microsoft UICC Compiler, which is used by the RibbonTools, is checking string length and will give an error message or cut the string length.

**Comment by harborsiem** [comment]
> > What do you mean with incorrect bound? Can you send a small project? NullReferenceException should not occur.
> 
> Debug mode: ![image](https://private-user-images.githubusercontent.com/142982913/317565914-78709da2-0dce-4412-8b53-0d682e0d0fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTA1OTgsIm5iZiI6MTcxMTYxMDI5OCwicGF0aCI6Ii8xNDI5ODI5MTMvMzE3NTY1OTE0LTc4NzA5ZGEyLTBkY2UtNDQxMi04YjUzLTBkNjgyZTBkMGZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNzE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmQ5Mzc4ZWIyYzYxOGJiZjhhYjdkZWZlNzUwZTE4ZmMzZWUwMjQ2MDE1NjdhYTQ2ZmQyYzMxMzVlYWU2MDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pJQCMeoWnriDqTmzc16L70gezd-XsCh6xo45zoM4-ug)
> 
> Release mode: ![image](https://private-user-images.githubusercontent.com/142982913/317565772-eede0cc3-2931-4bc1-b41d-5280b97cf234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTA1OTgsIm5iZiI6MTcxMTYxMDI5OCwicGF0aCI6Ii8xNDI5ODI5MTMvMzE3NTY1NzcyLWVlZGUwY2MzLTI5MzEtNGJjMS1iNDFkLTUyODBiOTdjZjIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNzE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODU3MTJjNGY1NDY4ZDNkMjI3NTkyYWM0YTFiMTgyNmEwZGM3OWVkNGYxZDM3YWZhZDBmZjA1MTZkMTc1YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I-0yYT0zG9xWt06oqdE15cZoHKCB2F8uG5x9egmDqfE)

Some more checks have to be done in the old code. Thanks for helping.

**Comment by kelilive** [comment]
Sorry, I didn't know that this was some of what Microsoft defined, I understand, thank you very much.

Then I think these two attributes should coexist to avoid the vertical and non-centered problem. In addition, the length of this attribute can actually be tested, and you can add length limit logic to the software.
