### ISSUE TITLE
RibbonItems Custom Namespace

### ISSUE THREAD

**Issue by ktwrd** [harborsiem/WindowsRibbon#18]
A really useful QoL feature would be to add the ability to change the namespace that the `RibbonItems.designer.cs` file uses.

This would be really useful for projects that have multiple Forms that all use completely different Ribbons, since Mode Changing can be a bit weird and you can actually reach the maximum number of items in a Ribbon.

A good place to configure the `RibbonItems` namespace would be in the Properties of the Root Ribbon element.

**Comment by harborsiem** [comment]
Did you see the hint for generating different RibbonItems classes (up to 10) for different forms. [Hint](https://github.com/harborsiem/WindowsRibbon/wiki/Wrapper-class-RibbonItems).
See also my project [ElemntViewer](https://github.com/harborsiem/ELEMNTViewer). In this project I use RibbonMarkup.xml which results in a RibbonItems.designer.cs for the main form and RibbonMarkup1.xml which results in RibbonItems1.designer.cs for an other form.

**Comment by ktwrd** [comment]
Yeah I understand that but what if you have an application where there are more than 10 ribbons required?

**Comment by ktwrd** [comment]
With how unnecessariarly large the application I'm working on, yes. It also becomes a problem where multiple libraries use the Ribbon controls and they have conflicting class names, and things might (and most likely will) break when that happens.

**Comment by harborsiem** [comment]
solved in version V2.16.0
