### ISSUE TITLE
RibbonPreview doesn't build under windows 10

### ISSUE THREAD

**Issue by riadbaziz** [harborsiem/WindowsRibbon#2]
I modified the template and specified the correct paths under windows 10 but the tool can't build the xml file, can you edit the tool for working under windows 10. Thanks

**Comment by harborsiem** [comment]
Please delete your template.bat file. Then start the build again. The build will generate a new template.bat with correct paths.
The RibbonPreview is working well under Windows 10 on my Computer.

**Comment by tajbender** [comment]
On mine as well, no problems so far.

@riadbaziz: You may take a look at my project, if this may be helpful: https://github.com/electrifier/electrifier
