### ISSUE TITLE
[Bug report] Spinner its decimal value can not initialized

### ISSUE THREAD

**Issue by xieguigang** [harborsiem/WindowsRibbon#3]
Hi,

Many thanks to your great job! This project is a great UI library for WinForm, and the demo in this repository is very useful to me. But after run each demo in this project, I found that there is a small bug about initialize the spinner its decimal value in demo project ``05-Spinner``: the spinner its decimal value is always ZERO at no matter what value i set to its decimal value property in the form load event. I'm not sure what is going wrong...

I'm looking forward to hearing from you soon, good luck.

**Comment by harborsiem** [comment]
Hi,

I have done a new release for the Ribbon library. Now the Spinnner DecimalValue worked as expected.

**Comment by xieguigang** [comment]
Hi,

I've try the latest release, the spinner it works, thank you very much.😊
