### ISSUE TITLE
FatalExecutionEngineError when accessing ContextAvailable

### ISSUE THREAD

**Issue by scholle** [harborsiem/WindowsRibbon#4]
If you change the sample try to check the Value of tabGroupTableTools.ContextAvailable first (sample 14-ContextualTabs) by 

**if (_tabGroupTableTools.ContextAvailable != ContextAvailability.Active)**
        _tabGroupTableTools.ContextAvailable = ContextAvailability.Active;

you will get the **FatalExecutionEngineError**. I checked the source and found the Problem: Ich you change in \Ribbon\Controls\Properties\ContextAvailablePropertiesProvider.cs line 78 from

return (ContextAvailability)(**_uint_**)uintValue.Value;

to 

return (ContextAvailability)(**_int_**)uintValue.Value;

the Error is gone.

Scholle

**Comment by harborsiem** [comment]
Many thanks for your help.
