### ISSUE TITLE
Dark Mode/Dark Theme

### ISSUE THREAD

**Issue by scholle** [harborsiem/WindowsRibbon#8]
Hi,

is it possible to switch to Dark Mode/Dark Theme? Does MS provide a Dark Theme solution?

Thanks
Scholle

**Comment by harborsiem** [comment]
Hi,
I think there is actually no (easy) way for a Dark Theme solution. MS is working on a solution, see [Themes Implementation in Winforms](https://github.com/dotnet/winforms/issues/5166). But I don't know the MS solution works for the Ribbon too.
I think the MS apps "Windows Explorer", "Wordpad" and "Paint" are also using the Windows Ribbon, but are programmed in C++. In Windows Explorer you can see, that the Dark Mode is working, Wordpad and Paint are not working.

**Comment by harborsiem** [comment]
You can set Ribbon Property DarkModeRibbon for activating Dark Mode only for Ribbon. See also Changelog.md for an example with Dark Mode in the Title Bar
